//
//  HomeInteractor.swift
//  UIKitCleanSwiftV.I.P
//
//  Created by Juho JUNG on 13/07/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
    func getCountries(request: Home.FetchCountry.Request)
}

protocol HomeDataStore {
    var countries: [Country]? { get }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    var countries: [Country]?
    
  var presenter: HomePresentationLogic?
  var worker: HomeWorker?
  
  // MARK: Do something
  
    func getCountries(request: Home.FetchCountry.Request) {
    worker = HomeWorker()
        worker?.fetchCountryData { result in
            switch result {
            case Result.success(let countryData):
                self.countries = countryData
                let response = Home.FetchCountry.Response(countries: countryData)
                self.presenter?.presentSomething(response: response)
            case Result.failure(let error):
                print("\(error.localizedDescription)")
            }
        }
  }
}
