//
//  HomeRouter.swift
//  UIKitCleanSwiftV.I.P
//
//  Created by Juho JUNG on 13/07/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc
protocol HomeRoutingLogic {
  func routeToDetailVC()
}

protocol HomeDataPassing {
  var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
  weak var viewController: HomeViewController?
  var dataStore: HomeDataStore?
  
  // MARK: Routing
  
  func routeToDetailVC() {
    let destinationVC = DetailViewController()
    if let viewController,
       let dataStore,
       var destinationDataStore = destinationVC.router?.dataStore
    {
      navigateToDetailVC(source: viewController,
                         destination: destinationVC)
      passDataToSomewhere(source: dataStore, destination: &destinationDataStore)
    }
//    if let segue = segue {
//        guard let destinationVC = segue.destination as? DetailViewController else { return }
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//    } else {
//      let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "DetailViewController") as! DetailViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//      navigateToDetailVC(source: viewController!, destination: destinationVC)
//    }
  }

  // MARK: Navigation
  
  func navigateToDetailVC(source: HomeViewController, destination: DetailViewController) {
    source.navigationController?.pushViewController(destination, animated: true)
  }
  
  // MARK: Passing data
  
  func passDataToSomewhere(source: HomeDataStore, destination: inout DetailDataStore) {
    let test = viewController?.HomeTableView.indexPathForSelectedRow?.row
    destination.countryName = source.countries?[test!]
  }
}
