//
//  DetailPresenter.swift
//  UIKitCleanSwiftV.I.P
//
//  Created by Juho JUNG on 20/07/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic
{
  func presentSomething(response: Detail.GetDetail.Response)
}

class DetailPresenter: DetailPresentationLogic
{
  weak var viewController: DetailDisplayLogic?
  
  // MARK: Do something
  
    func presentSomething(response: Detail.GetDetail.Response)
  {
      let viewModel = Detail.GetDetail.ViewModel.DisplayedCountry(name: response)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
